app = 'betleague'
primary_region = 'gru'

[build]

[env]
  PORT = '3001'
  FRONTEND_URL = 'https://betleague.fly.dev'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 50
    soft_limit = 25

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
